/**
 * @file namespace.h
 *
 * Maps every public name of this library into its version namespace.
 *
 * Kept in one file rather than beside each declaration: a type rename has to
 * be in effect before any struct tag that uses the name, and an internal
 * header may define such a tag without including the public header that
 * declares the typedef.
 *
 * `make check-symbols` fails if an exported symbol is missing from this list.
 *
 * See CONVENTIONS.md section 4.
 *
 * Copyright 2026 by Corey Pennycuff
 */

#ifndef CJELLY_NAMESPACE_H
#define CJELLY_NAMESPACE_H

#include <cjelly/libver.h>

/// @cond HIDDEN_SYMBOLS
#define cj_bindless_set_color CJ_NS(cj_bindless_set_color)
#define cj_bindless_update_split_from_colorMul CJ_NS(cj_bindless_update_split_from_colorMul)
#define cj_buffer_create CJ_NS(cj_buffer_create)
#define cj_buffer_descriptor_slot CJ_NS(cj_buffer_descriptor_slot)
#define cj_buffer_release CJ_NS(cj_buffer_release)
#define cj_buffer_retain CJ_NS(cj_buffer_retain)
#define cj_capture_free CJ_NS(cj_capture_free)
#define cj_capture_pixel CJ_NS(cj_capture_pixel)
#define cj_capture_write_png CJ_NS(cj_capture_write_png)
#define cj_engine_basic CJ_NS(cj_engine_basic)
#define cj_engine_bindless CJ_NS(cj_engine_bindless)
#define cj_engine_bindless_layout CJ_NS(cj_engine_bindless_layout)
#define cj_engine_bindless_pool CJ_NS(cj_engine_bindless_pool)
#define cj_engine_color_pipeline CJ_NS(cj_engine_color_pipeline)
#define cj_engine_command_pool CJ_NS(cj_engine_command_pool)
#define cj_engine_create CJ_NS(cj_engine_create)
#define cj_engine_create_buffer CJ_NS(cj_engine_create_buffer)
#define cj_engine_create_sampler CJ_NS(cj_engine_create_sampler)
#define cj_engine_create_texture CJ_NS(cj_engine_create_texture)
#define cj_engine_destroy_buffer CJ_NS(cj_engine_destroy_buffer)
#define cj_engine_destroy_sampler CJ_NS(cj_engine_destroy_sampler)
#define cj_engine_destroy_texture CJ_NS(cj_engine_destroy_texture)
#define cj_engine_device CJ_NS(cj_engine_device)
#define cj_engine_device_index CJ_NS(cj_engine_device_index)
#define cj_engine_ensure_render_pass CJ_NS(cj_engine_ensure_render_pass)
#define cj_engine_export_context CJ_NS(cj_engine_export_context)
#define cj_engine_get_bindless_info CJ_NS(cj_engine_get_bindless_info)
#define cj_engine_get_current CJ_NS(cj_engine_get_current)
#define cj_engine_graphics_queue CJ_NS(cj_engine_graphics_queue)
#define cj_engine_import_context CJ_NS(cj_engine_import_context)
#define cj_engine_init CJ_NS(cj_engine_init)
#define cj_engine_init_vulkan CJ_NS(cj_engine_init_vulkan)
#define cj_engine_instance CJ_NS(cj_engine_instance)
#define cj_engine_physical_device CJ_NS(cj_engine_physical_device)
#define cj_engine_present_queue CJ_NS(cj_engine_present_queue)
#define cj_engine_render_pass CJ_NS(cj_engine_render_pass)
#define cj_engine_res_alloc CJ_NS(cj_engine_res_alloc)
#define cj_engine_res_release CJ_NS(cj_engine_res_release)
#define cj_engine_res_retain CJ_NS(cj_engine_res_retain)
#define cj_engine_res_slot CJ_NS(cj_engine_res_slot)
#define cj_engine_set_current CJ_NS(cj_engine_set_current)
#define cj_engine_shutdown CJ_NS(cj_engine_shutdown)
#define cj_engine_shutdown_device CJ_NS(cj_engine_shutdown_device)
#define cj_engine_shutdown_vulkan CJ_NS(cj_engine_shutdown_vulkan)
#define cj_engine_textured CJ_NS(cj_engine_textured)
#define cj_engine_wait_idle CJ_NS(cj_engine_wait_idle)
#define cj_handle_alloc CJ_NS(cj_handle_alloc)
#define cj_handle_release CJ_NS(cj_handle_release)
#define cj_handle_retain CJ_NS(cj_handle_retain)
#define cj_handle_slot CJ_NS(cj_handle_slot)
#define cj_keycode_to_string CJ_NS(cj_keycode_to_string)
#define cj_mouse_button_is_pressed CJ_NS(cj_mouse_button_is_pressed)
#define cj_mouse_get_position CJ_NS(cj_mouse_get_position)
#define cj_poll_events CJ_NS(cj_poll_events)
#define cj_request_stop CJ_NS(cj_request_stop)
#define cj_result_str CJ_NS(cj_result_str)
#define cj_rgraph_add_blur_node CJ_NS(cj_rgraph_add_blur_node)
#define cj_rgraph_add_color_node CJ_NS(cj_rgraph_add_color_node)
#define cj_rgraph_add_model_node CJ_NS(cj_rgraph_add_model_node)
#define cj_rgraph_add_textured_node CJ_NS(cj_rgraph_add_textured_node)
#define cj_rgraph_bind_texture CJ_NS(cj_rgraph_bind_texture)
#define cj_rgraph_create CJ_NS(cj_rgraph_create)
#define cj_rgraph_destroy CJ_NS(cj_rgraph_destroy)
#define cj_rgraph_execute CJ_NS(cj_rgraph_execute)
#define cj_rgraph_execute_prepass CJ_NS(cj_rgraph_execute_prepass)
#define cj_rgraph_recompile CJ_NS(cj_rgraph_recompile)
#define cj_rgraph_set_i32 CJ_NS(cj_rgraph_set_i32)
#define cj_run CJ_NS(cj_run)
#define cj_run_once CJ_NS(cj_run_once)
#define cj_run_with_config CJ_NS(cj_run_with_config)
#define cj_sampler_create CJ_NS(cj_sampler_create)
#define cj_sampler_descriptor_slot CJ_NS(cj_sampler_descriptor_slot)
#define cj_sampler_release CJ_NS(cj_sampler_release)
#define cj_sampler_retain CJ_NS(cj_sampler_retain)
#define cj_texture_create CJ_NS(cj_texture_create)
#define cj_texture_descriptor_slot CJ_NS(cj_texture_descriptor_slot)
#define cj_texture_release CJ_NS(cj_texture_release)
#define cj_texture_retain CJ_NS(cj_texture_retain)
#define cj_version_runtime CJ_NS(cj_version_runtime)
#define cj_window_begin_frame CJ_NS(cj_window_begin_frame)
#define cj_window_capture CJ_NS(cj_window_capture)
#define cj_window_capture_mouse CJ_NS(cj_window_capture_mouse)
#define cj_window_clear_dirty CJ_NS(cj_window_clear_dirty)
#define cj_window_create CJ_NS(cj_window_create)
#define cj_window_destroy CJ_NS(cj_window_destroy)
#define cj_window_execute CJ_NS(cj_window_execute)
#define cj_window_frame_index CJ_NS(cj_window_frame_index)
#define cj_window_get_dpi_scale CJ_NS(cj_window_get_dpi_scale)
#define cj_window_get_position CJ_NS(cj_window_get_position)
#define cj_window_get_size CJ_NS(cj_window_get_size)
#define cj_window_get_state CJ_NS(cj_window_get_state)
#define cj_window_has_mouse_capture CJ_NS(cj_window_has_mouse_capture)
#define cj_window_is_high_dpi CJ_NS(cj_window_is_high_dpi)
#define cj_window_mark_dirty CJ_NS(cj_window_mark_dirty)
#define cj_window_mark_dirty_with_reason CJ_NS(cj_window_mark_dirty_with_reason)
#define cj_window_on_close CJ_NS(cj_window_on_close)
#define cj_window_on_focus CJ_NS(cj_window_on_focus)
#define cj_window_on_frame CJ_NS(cj_window_on_frame)
#define cj_window_on_key CJ_NS(cj_window_on_key)
#define cj_window_on_mouse CJ_NS(cj_window_on_mouse)
#define cj_window_on_move CJ_NS(cj_window_on_move)
#define cj_window_on_resize CJ_NS(cj_window_on_resize)
#define cj_window_on_state_change CJ_NS(cj_window_on_state_change)
#define cj_window_present CJ_NS(cj_window_present)
#define cj_window_release_mouse CJ_NS(cj_window_release_mouse)
#define cj_window_rerecord_bindless_color CJ_NS(cj_window_rerecord_bindless_color)
#define cj_window_resize CJ_NS(cj_window_resize)
#define cj_window_set_max_fps CJ_NS(cj_window_set_max_fps)
#define cj_window_set_position CJ_NS(cj_window_set_position)
#define cj_window_set_redraw_policy CJ_NS(cj_window_set_redraw_policy)
#define cj_window_set_render_graph CJ_NS(cj_window_set_render_graph)
#define cj_window_set_state CJ_NS(cj_window_set_state)
#define cjelly_application_add_device_extension CJ_NS(cjelly_application_add_device_extension)
#define cjelly_application_add_instance_extension CJ_NS(cjelly_application_add_instance_extension)
#define cjelly_application_close_all_windows CJ_NS(cjelly_application_close_all_windows)
#define cjelly_application_create CJ_NS(cjelly_application_create)
#define cjelly_application_create_command_pools CJ_NS(cjelly_application_create_command_pools)
#define cjelly_application_create_logical_device CJ_NS(cjelly_application_create_logical_device)
#define cjelly_application_destroy CJ_NS(cjelly_application_destroy)
#define cjelly_application_find_window_by_handle CJ_NS(cjelly_application_find_window_by_handle)
#define cjelly_application_get_current CJ_NS(cjelly_application_get_current)
#define cjelly_application_get_windows CJ_NS(cjelly_application_get_windows)
#define cjelly_application_init CJ_NS(cjelly_application_init)
#define cjelly_application_on_shutdown CJ_NS(cjelly_application_on_shutdown)
#define cjelly_application_on_signal CJ_NS(cjelly_application_on_signal)
#define cjelly_application_register_signal_handlers CJ_NS(cjelly_application_register_signal_handlers)
#define cjelly_application_register_window CJ_NS(cjelly_application_register_window)
#define cjelly_application_set_current CJ_NS(cjelly_application_set_current)
#define cjelly_application_set_device_type CJ_NS(cjelly_application_set_device_type)
#define cjelly_application_set_required_gpu_memory CJ_NS(cjelly_application_set_required_gpu_memory)
#define cjelly_application_set_required_vulkan_version CJ_NS(cjelly_application_set_required_vulkan_version)
#define cjelly_application_set_validation CJ_NS(cjelly_application_set_validation)
#define cjelly_application_should_shutdown CJ_NS(cjelly_application_should_shutdown)
#define cjelly_application_supports_bindless_rendering CJ_NS(cjelly_application_supports_bindless_rendering)
#define cjelly_application_unregister_window CJ_NS(cjelly_application_unregister_window)
#define cjelly_application_window_count CJ_NS(cjelly_application_window_count)
#define cjelly_create_bindless_color_square_resources_ctx CJ_NS(cjelly_create_bindless_color_square_resources_ctx)
#define cjelly_create_bindless_resources_ctx CJ_NS(cjelly_create_bindless_resources_ctx)
#define cjelly_destroy_bindless_resources CJ_NS(cjelly_destroy_bindless_resources)
#define processWindowEvents CJ_NS(processWindowEvents)
/// @endcond

#endif // CJELLY_NAMESPACE_H
